lewis6991/gitsigns.nvim

lua/gitsigns.lua
Fixes signs appearing on directory listings such as Dirvish.
=> fix: ignore directory listings.

lua/gitsigns/status.lua, teal/gitsigns/status.tl
=> fix: invalid buffer id while clearing status

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/config.lua, lua/gitsigns/hunks.lua, teal/gitsigns.tl, teal/gitsigns/config.tl, teal/gitsigns/hunks.tl, teal/gitsigns/types.tl, types/types.d.tl
Added `config.use_decoration_provider` to update signs instead of applying all signs on every update. This is experimental and must explicitly enabled.
=> Improve performance on large files

doc/gitsigns.txt
=> Fix typo in the doc

README.md, lua/gitsigns.lua, lua/gitsigns/config.lua, lua/gitsigns/debug.lua, lua/gitsigns/git.lua, lua/gitsigns/util.lua, teal/gitsigns.tl, teal/gitsigns/config.tl, teal/gitsigns/debug.tl, teal/gitsigns/git.tl, teal/gitsigns/util.tl, test/gitsigns_spec.lua
- Rename text_object() -> select_hunk()
- Add the Gitsigns command
=> Git version checking

lua/gitsigns.lua, lua/gitsigns/git.lua, teal/gitsigns.tl, teal/gitsigns/git.tl, test/gitsigns_spec.lua, types/plenary/async_lib/async.d.tl
Reverts lewis6991/gitsigns.nvim#134
=> Revert "Refactor git commands to be more OOP"

lua/gitsigns.lua, teal/gitsigns.tl, types/types.d.tl
* disable gitsign on diff mode
* add support to git `submodule
```
fugitive:///home/wind/projects/abcdef/.git/modules/web-components//198faedae29cd87cc8f839e22d347e6c6e0ce17f/src/app/index.html
```
=> fugitive fix for git signs

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/util.lua, teal/gitsigns.tl, teal/gitsigns/util.tl, test/gitsigns_spec.lua
Analogous to fugitives `:Gvdiffsplit`, see :`help gitsigns.diffthis()`
=> Added diffthis()

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> Respect wrap param sent to next_hunk() and prev_hunk()

doc/gitsigns.txt, lua/gitsigns/config.lua, lua/gitsigns/debug.lua, lua/gitsigns/highlight.lua, lua/gitsigns/manager.lua, teal/gitsigns.tl, teal/gitsigns/config.tl, teal/gitsigns/debug.tl, teal/gitsigns/highlight.tl, teal/gitsigns/manager.tl, test/highlights_spec.lua
- Simplify code
- Search for more known highlight groups, e.g:
- GitGutterAdd
- SignifySignAdd
- DiffAddedGutter
- diffAdded
- DiffAdd'
=> Improve highlight derivation

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> Re-add 'full' argument to blame_line()

doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/hunks.lua, teal/gitsigns/actions.tl, teal/gitsigns/hunks.tl, types/types.d.tl
=> show status message when navigating hunks

doc/gitsigns.txt, lua/gitsigns/config.lua, lua/gitsigns/current_line_blame.lua, lua/gitsigns/util.lua, teal/gitsigns/config.tl, teal/gitsigns/current_line_blame.tl, teal/gitsigns/util.tl
=> switch example to get current line blame as relative time string

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> Add toggle_word_diff()

lua/gitsigns/actions.lua, lua/gitsigns/hunks.lua, lua/gitsigns/popup.lua, teal/gitsigns/actions.tl, teal/gitsigns/hunks.tl, teal/gitsigns/popup.tl
- Add title to hunk preview
- Keep hunk preview open when navigating hunks
=> Improvements to preview_hunk()

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, lua/gitsigns/status.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl, teal/gitsigns/status.tl, test/gs_helpers.lua
- Ensure attach() is not run concurrently for a specific buffer
- Rework status vars
- Dirty fix for #263
=> Misc changees

README.md, doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/git.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/git.tl, teal/gitsigns/manager.tl, types/types.d.tl
Set the quickfix/location list with hunks from either:
- A specific buffer
- All attached buffers
- All modified files for each gitdir of each attached buffer
=> feat: Add setqflist and setloclist

lua/gitsigns.lua, lua/gitsigns/debug.lua, teal/gitsigns.tl, teal/gitsigns/debug.tl, test/gitsigns_spec.lua
=> Disable during vimgrep

lua/gitsigns/cache.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, teal/gitsigns/cache.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl, test/gs_helpers.lua
=> Don't re-apply signs if hunk heads don't change

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> Print warning when navigating to hunk in an unmodified file

lua/gitsigns/popup.lua, teal/gitsigns/popup.tl
=> Make popup close on BufLeave

lua/gitsigns/popup.lua, teal/gitsigns/popup.tl
=> Make popup close on BufLeave, take 2

gitsigns-scm-1.rockspec
revival of #281 
- feat: add rockspec gitsigns.nvim
- copy doc too otherwise it's not accessible
=> feat: add rockspec

lua/gitsigns.lua, lua/gitsigns/config.lua, lua/gitsigns/debug.lua, lua/gitsigns/git.lua, lua/gitsigns/highlight.lua, lua/gitsigns/manager.lua, teal/gitsigns.tl, teal/gitsigns/config.tl, teal/gitsigns/debug.tl, teal/gitsigns/git.tl, teal/gitsigns/highlight.tl, teal/gitsigns/manager.tl
To help diagnose issues with malformed process output
=> Add config._verbose

lua/gitsigns/popup.lua, teal/gitsigns/popup.tl, types/types.d.tl
.. when calculating height
Fixes #311
=> fix(preview): Account for wrapped lines

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl, types/plenary/async/util.d.tl
=> Fix: make setloclist()/setqflist() synchronous

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
This should fix all toggle_*() which were previously broken by fc170b4e
=> fix(refresh): invalidate hunks when refreshing

lua/gitsigns/config.lua, lua/gitsigns/debug.lua, teal/gitsigns/config.tl, teal/gitsigns/debug.tl, types/types.d.tl
=> Use vim.notify for user messages

doc/gitsigns.txt
=> fix(doc): duplicate tag gitsigns-config-current_line_blame

.github/workflows/ci.yml, README.md, doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/config.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/diff_int/xdl_diff_ffi.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/config.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/diff_int/xdl_diff_ffi.tl, teal/gitsigns/manager.tl, types/types.d.tl
Requires PR [neovim/neovim/#14536](https://github.com/neovim/neovim/pull/14536)
=> Add support for vim.xdl_diff

doc/gitsigns.txt, lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> feat(blame_line): Show hunk in preview

lua/gitsigns/actions.lua, lua/gitsigns/git.lua, teal/gitsigns/actions.tl, teal/gitsigns/git.tl, teal/gitsigns/popup.tl
- Refactored
- Fixed incorrect highlighting of removed lines in hunk
- Show which hunk from the commit the blame is for
- Fix issues when hunk is from a different filename
=> feat(blame_line): more improvements and fixes

lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl
=> fix(current_line_blame): set hl_mode='combine' on extmark

lua/gitsigns/manager.lua, teal/gitsigns/manager.tl
=> fix: don't error on Ctrl-c in insert mode (#346)

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/git.lua, teal/gitsigns.tl, teal/gitsigns/git.tl, test/gitsigns_spec.lua, test/index_watcher_spec.lua, types/types.d.tl
Head value based on cwd
Resolves #344
=> feat: add g:gitsigns_head

gen_help.lua, lua/gitsigns/config.lua, teal/gitsigns/config.tl, test/gitsigns_spec.lua
=> handle deprecated fields more generically

README.md, doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/config.lua, lua/gitsigns/diff_ext.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/manager.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/config.tl, teal/gitsigns/diff_ext.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/manager.tl, test/gitsigns_spec.lua, types/types.d.tl
- DEPRECATED diff_algorithm
replaced with diff_opts.algorithm
- DEPRECATED use_internal_diff
replaced with diff_opts.internal
- ADDED diff_opts.indent_heuristic
=> Add config.diff_opts and deprecate fields

lua/gitsigns/actions.lua, lua/gitsigns/git.lua, teal/gitsigns/actions.tl, teal/gitsigns/git.tl
=> fix(setqflist): handle modified submodules

lua/gitsigns/actions.lua, lua/gitsigns/git.lua, teal/gitsigns/actions.tl, teal/gitsigns/git.tl, test/gitsigns_spec.lua, test/gs_helpers.lua, test/index_watcher_spec.lua
=> fix(blame_line): don't error in fresh repo

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> fix(repeat): when preview is open

doc/gitsigns.txt, lua/gitsigns/actions.lua, teal/gitsigns/actions.tl, types/types.d.tl
=> feat(nav_hunk): respect 'foldopen' when jumping

lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl
=> fix(autocmd): end gitsigns_blame augroup properly

lua/gitsigns/actions.lua, lua/gitsigns/diff_ext.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/diff_ext.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl, test/gitsigns_spec.lua
So added and removed lines are kept in separate tables
=> chore(refactor): refactor Hunk object

README.md
=> chore(doc): add integrations to README

CONTRIBUTING.md, lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
Closes #403. I also fixed a couple of typos I found in CONTRIBUTING.md and updated the null-ls setup instructions there.
=> fix(actions): correctly check if staged_diffs is empty

doc/gitsigns.txt, lua/gitsigns/config.lua, teal/gitsigns/config.tl
You updated the README but not the default config ;-)
=> fix(blame): Adapt default config to latest blame changes

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> Adds cursor position to the jump list before `next_hunk` and `prev_hunk`

lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl
=> feat(current_line_blame): add caching of blame

README.md, doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/config.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/hunks.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/config.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/hunks.tl, test/actions_spec.lua, test/gitsigns_spec.lua, test/gs_helpers.lua, types/types.d.tl
=> feat(actions): true partial hunk staging

doc/gitsigns.txt, lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
If true, open the qf/loc list viewer. Defaults to true.
Resolves #415
=> feat(setqflist): Add 'open' option

lua/gitsigns/diff_ext.lua, lua/gitsigns/util.lua, teal/gitsigns/diff_ext.tl, teal/gitsigns/util.tl
=> cleanup util

doc/gitsigns.txt, etc/doc_template.txt, gen_help.lua, lua/gitsigns.lua, lua/gitsigns/actions.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl
- Move function docs to comments in actions.tl
- Rewrite gen_help.lua to use a template
=> Automate docs more

lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/cache.lua, lua/gitsigns/git.lua, lua/gitsigns/manager.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/cache.tl, teal/gitsigns/git.tl, teal/gitsigns/manager.tl, test/gitsigns_spec.lua
=> fix(windows): Fix CRLF handling

lua/gitsigns/manager.lua, teal/gitsigns/manager.tl
=> fix(): check valid buffers after schedule

lua/gitsigns.lua, teal/gitsigns.tl, types/types.d.tl
=> Use nvim_add_user_command if available

lua/gitsigns.lua, lua/gitsigns/diff_ext.lua, lua/gitsigns/git.lua, teal/gitsigns.tl, teal/gitsigns/diff_ext.tl, teal/gitsigns/git.tl, test/gitsigns_spec.lua
Small refactoring to put all git-related code to a single file
=> Move git-related code to git.tl file

lua/gitsigns/git.lua, teal/gitsigns/git.tl
=> fix(): do not run fs_realpath on nil dir

.github/workflows/ci.yml
=> chore(ci): change Neovim v0.5.0 -> v0.6.1

lua/gitsigns/config.lua, teal/gitsigns/config.tl
=> feat(blame): enable blame cache by default

README.md, doc/gitsigns.txt, gen_help.lua, lua/gitsigns/config.lua, teal/gitsigns/config.tl, types/types.d.tl
- Removed default keymappings.
- Instead on_attach should be used.
=> break!: deprecate config.keymaps

doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/config.lua, teal/gitsigns/actions.tl, teal/gitsigns/config.tl
- Added config.diff_opt.vertical
- When running diffthis, only enable diffmode on the correct windows.
Fixes: #456, #455
=> fix(actions): diffthis fixes

.github/workflows/ci.yml, lua/gitsigns/highlight.lua, teal/gitsigns/highlight.tl, types/types.d.tl
Requires neovim master with commit 5be2cdd91 (PR [neovim/neovim #17187](https://github.com/neovim/neovim/pull/17187))
=> refactor(highlights)!: Use nvim_set_hl for setting highlights

lua/gitsigns/repeat.lua, teal/gitsigns/repeat.tl
=> fix(repeat): regression

lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl, types/types.d.tl
=> fix(blame): reduce flicker when on same line

lua/gitsigns/actions.lua, lua/gitsigns/util.lua, teal/gitsigns/actions.tl, teal/gitsigns/util.tl
=> fix(dos): don't insert extra carriage returns

lua/gitsigns/async.lua, teal/gitsigns/async.tl
=> fix(compat): fix missing support for PUC Lua

doc/gitsigns.txt, gitsigns.nvim-scm-1.rockspec, lua/gitsigns/actions.lua, lua/gitsigns/async.lua, lua/gitsigns/cache.lua, lua/gitsigns/debounce.lua, lua/gitsigns/diffthis.lua, lua/gitsigns/git.lua, lua/gitsigns/manager.lua, lua/gitsigns/util.lua, teal/gitsigns/actions.tl, teal/gitsigns/async.tl, teal/gitsigns/cache.tl, teal/gitsigns/debounce.tl, teal/gitsigns/diffthis.tl, teal/gitsigns/git.tl, teal/gitsigns/manager.tl, teal/gitsigns/util.tl, types/types.d.tl
=> fix(diffthis): update diff when staging hunks

doc/gitsigns.txt, lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> feat(toggle): return current value

gitsigns.nvim-scm-1.rockspec, lua/gitsigns/actions.lua, lua/gitsigns/async.lua, lua/gitsigns/config.lua, lua/gitsigns/diff.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/async.tl, teal/gitsigns/config.tl, teal/gitsigns/diff.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/manager.tl, types/types.d.tl
Requires https://github.com/neovim/neovim/pull/15658
=> feat(diff): run xdiff on a separate thread

.github/workflows/ci.yml
=> chore(ci): add Neovim 0.7 to build matrix

lua/gitsigns.lua, lua/gitsigns/git.lua, teal/ffi.d.tl, teal/gitsigns.tl, teal/gitsigns/git.tl, types/types.d.tl
=> fix: use iconv for non-utf-8 encodings

lua/gitsigns.lua, teal/gitsigns.tl
=> feat: detect changes of g:gitsigns_head

lua/gitsigns.lua, lua/gitsigns/manager.lua, teal/gitsigns.tl, teal/gitsigns/manager.tl
=> refactor: move more stuff into manager.tl

lua/gitsigns/nvim/callbacks.lua, lua/gitsigns/nvim/command_compat.lua, teal/gitsigns/nvim/callbacks.tl, teal/gitsigns/nvim/command_compat.tl
=> fix: commands for 0.6

lua/gitsigns/hunks.lua, teal/gitsigns/hunks.tl
=> fix: bad sign calculation

lua/gitsigns/actions.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl
=> refactor: simplify hunk type

lua/gitsigns/actions.lua, lua/gitsigns/cache.lua, lua/gitsigns/debug.lua, lua/gitsigns/diffthis.lua, teal/gitsigns/actions.tl, teal/gitsigns/cache.tl, teal/gitsigns/debug.tl, teal/gitsigns/diffthis.tl
=> refactor: removed unused code

lua/gitsigns/util.lua, teal/gitsigns/util.tl
=> fix(preview): handle % chars properly

lua/gitsigns.lua, lua/gitsigns/util.lua, teal/gitsigns.tl, teal/gitsigns/util.tl, test/unit_spec.lua
=> test: improve unit tests

lua/gitsigns.lua, lua/gitsigns/argparse.lua, lua/gitsigns/test.lua, lua/gitsigns/util.lua, teal/gitsigns.tl, teal/gitsigns/argparse.tl, teal/gitsigns/test.tl, teal/gitsigns/util.tl, test/unit_spec.lua
=> refactor: move unit tests

lua/gitsigns/cache.lua, lua/gitsigns/manager.lua, teal/gitsigns/cache.tl, teal/gitsigns/manager.tl, test/gitsigns_spec.lua
=> fix: improve fix for #521

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/async.lua, lua/gitsigns/cache.lua, lua/gitsigns/debounce.lua, lua/gitsigns/diffthis.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/async.tl, teal/gitsigns/cache.tl, teal/gitsigns/debounce.tl, teal/gitsigns/diffthis.tl, teal/gitsigns/manager.tl
Similar to diffthis, except diff mode is not enabled.
=> feat: add `show` action

lua/gitsigns/diffthis.lua, teal/gitsigns/diffthis.tl, types/types.d.tl
=> feat(diffthis): respect 'splitright'

lua/gitsigns/actions.lua, teal/gitsigns/actions.tl
=> fix(diffthis): apply mods properly

lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl
=> fix(blame): prevent debounce from killing setup()

.github/workflows/ci.yml
=> ci: use Neovim nightly instead of master

lua/gitsigns/manager.lua, teal/gitsigns/manager.tl
=> fix(signs): make sure signs are always displayed

doc/gitsigns.txt, lua/gitsigns/config.lua, teal/gitsigns/config.tl, test/gitsigns_spec.lua
=> chore!: remove deprecated fields

lua/gitsigns/async.lua, teal/gitsigns/async.tl
~Use coroutine upvars to significantly simplify the implementation.~
~Inspired from https://github.com/neovim/neovim/issues/19624#issuecomment-1204867814~
Change of plan. Stick with the old implementation but simplify it a little.
=> feat(async): simpler implementation

lua/gitsigns/async.lua, teal/gitsigns/async.tl
=> fix(async): handle Lua 5.2 coroutines

doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/popup.lua, teal/gitsigns/actions.tl, teal/gitsigns/popup.tl, types/types.d.tl
I agree with your comment here: https://github.com/lewis6991/gitsigns.nvim/pull/609#issuecomment-1243940330
Made it to always attach to the popup if it's already open
=> feat(preview): attach to popup if already open

lua/gitsigns/manager.lua, teal/gitsigns/manager.tl
=> fix(word_diff): highlight last character on line

lua/gitsigns/popup.lua, teal/gitsigns/popup.tl
=> fix(preview): do not close other windows

lua/gitsigns/actions.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/manager.tl
=> fix: word diff

.github/workflows/ci.yml, Makefile
=> chore(ci): partition deps better

lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/current_line_blame.lua, lua/gitsigns/manager.lua, lua/gitsigns/status.lua, teal/gitsigns.tl, teal/gitsigns/actions.tl, teal/gitsigns/current_line_blame.tl, teal/gitsigns/manager.tl, teal/gitsigns/status.tl, types/types.d.tl
=> chore: update API usage

.github/workflows/ci.yml
- Remove redundant comments
- Bump all actions to latest stable
- Replace deprecated set-output with Github environment files
=> ci: clean up and update the workflow file

.github/workflows/ci.yml, Makefile, doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/diff_int.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl
=> feat(preview): add preview_hunk_inline()

README.md, doc/gitsigns.txt, lua/gitsigns/config.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, lua/gitsigns/signs/base.lua, teal/gitsigns/config.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl, teal/gitsigns/signs/base.tl, test/gitsigns_spec.lua, test/gs_helpers.lua
=> feat(signs): different add signs for untracked files

doc/gitsigns.txt, etc/doc_template.txt, lua/gitsigns/current_line_blame.lua, teal/gitsigns/current_line_blame.tl, types/types.d.tl
=> feat: add b:gitsigns_line_blame

lua/gitsigns/git.lua, teal/gitsigns/git.tl
=> fix: emit error on bad version check

lua/gitsigns/diff_ext.lua, teal/gitsigns/diff_ext.tl
=> fix(diff-ext): do not create unused temp files

lua/gitsigns/manager.lua, lua/gitsigns/util.lua, teal/gitsigns/manager.tl, teal/gitsigns/util.tl, test/gitdir_watcher_spec.lua, types/types.d.tl
=> fix(follow_files): do not rename if buffer name already exists

test/preload.lua
=> test: fix CI

lua/gitsigns/actions.lua, lua/gitsigns/cache.lua, lua/gitsigns/config.lua, lua/gitsigns/debug.lua, lua/gitsigns/highlight.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, lua/gitsigns/signs/base.lua, lua/gitsigns/signs/extmarks.lua, lua/gitsigns/signs/vimfn.lua, teal/gitsigns/actions.tl, teal/gitsigns/cache.tl, teal/gitsigns/config.tl, teal/gitsigns/debug.tl, teal/gitsigns/highlight.tl, teal/gitsigns/hunks.tl, teal/gitsigns/manager.tl, teal/gitsigns/signs/base.tl, teal/gitsigns/signs/extmarks.tl, teal/gitsigns/signs/vimfn.tl, types/vim/api.d.tl
Example: second hunk in the screenshot is staged:
=> staged signs (take 2)

lua/gitsigns/argparse.lua, teal/gitsigns/argparse.tl
=> feat: parse flags

lua/gitsigns/actions.lua, lua/gitsigns/popup.lua, teal/gitsigns/actions.tl, teal/gitsigns/popup.tl
=> fix: do not focus preview when navigating hunks

lua/gitsigns/async.lua, teal/gitsigns/async.tl, types/vim.d.tl
Migrate changes discussed in https://github.com/neovim/neovim/issues/19624
=> feat: yet another async implementation

lua/gitsigns.lua, lua/gitsigns/git.lua, lua/gitsigns/test.lua, teal/gitsigns.tl, teal/gitsigns/git.tl, teal/gitsigns/test.tl, types/vim.d.tl, types/vim/fn.d.tl
=> fix: use fugitive functions to parse fugitive:// url

lua/gitsigns/cli.lua, teal/gitsigns/cli.tl
=> fix(cli): print results of functions

doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/config.lua, lua/gitsigns/current_line_blame.lua, lua/gitsigns/highlight.lua, lua/gitsigns/manager.lua, teal/gitsigns/actions.tl, teal/gitsigns/config.tl, teal/gitsigns/highlight.tl, teal/gitsigns/manager.tl, types/vim.d.tl, types/vim/api.d.tl, types/vim/fn.d.tl
=> feat: improved preview_hunk_inline()

lua/gitsigns/diffthis.lua
Addresses https://github.com/lewis6991/gitsigns.nvim/issues/857
=> fix: Change awrap to wrap in diffthis.lua

lua/gitsigns/diff_int.lua, lua/gitsigns/git.lua, lua/gitsigns/util.lua, test/gitsigns_spec.lua
=> fix(diff): better handling of final newline

lua/gitsigns/watcher.lua
=> fix(watcher): check for detached buffers

doc/gitsigns.txt, lua/gitsigns/config.lua, lua/gitsigns/diff.lua, lua/gitsigns/diff_ext.lua, lua/gitsigns/diff_int.lua
=> feat(diffopt): add support for whitespace flags in diffopt

lua/gitsigns/git.lua
=> fix(git): respect env vars

lua/gitsigns/cache.lua
=> fix(blame): add line threshold for large files

lua/gitsigns/manager.lua, test/gitsigns_spec.lua, test/gs_helpers.lua, test/helpers.lua
=> fix: issue #888

README.md
https://github.com/nvimdev/lspsaga.nvim/blob/8c7e03e2851cd16219b3b2d05192473ac07025a7/lua/lspsaga/init.lua#L47
=> fix(README): correct default value Lspsaga integration.

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/highlight.lua, test/gitsigns_spec.lua, test/highlights_spec.lua
=> fix(hl): highlights for Nvim v0.9

lua/gitsigns/watcher.lua
Closes https://github.com/lewis6991/gitsigns.nvim/issues/956
=> fix(watcher): handler buffer check

lua/gitsigns/actions.lua
=> fix(blame): check buffer still exists after loading

doc/gitsigns.txt, etc/doc_template.txt, gen_help.lua, lua/gitsigns.lua, lua/gitsigns/actions.lua, lua/gitsigns/async.lua, lua/gitsigns/attach.lua, lua/gitsigns/cache.lua, lua/gitsigns/cli.lua, lua/gitsigns/current_line_blame.lua, lua/gitsigns/diff_int.lua, lua/gitsigns/diffthis.lua, lua/gitsigns/git.lua, lua/gitsigns/git/version.lua, lua/gitsigns/manager.lua, lua/gitsigns/watcher.lua
- simplify async code
Fixes: #906, #766
=> feat(actions): add callback to async actions

lua/gitsigns/hunks.lua, test/actions_spec.lua
=> fix(actions): prev_hunk works with wrap on line 1

doc/gitsigns.txt, etc/doc_template.txt, lua/gitsigns.lua, lua/gitsigns/manager.lua, lua/gitsigns/status.lua, test/actions_spec.lua
=> fix: trigger GitSignsUpdate autocmd more often

doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/cache.lua, lua/gitsigns/config.lua, lua/gitsigns/git.lua
=> feat(blame): support extra options

lua/gitsigns/actions.lua, lua/gitsigns/attach.lua, lua/gitsigns/diffthis.lua
=> fix: attach to fugitive and gitsigns buffers

doc/gitsigns.txt, lua/gitsigns.lua, lua/gitsigns/attach.lua, lua/gitsigns/current_line_blame.lua, lua/gitsigns/debug/log.lua, lua/gitsigns/git.lua, lua/gitsigns/manager.lua, lua/gitsigns/system.lua, lua/gitsigns/util.lua, test/actions_spec.lua, test/gitdir_watcher_spec.lua, test/gitsigns_spec.lua, test/gs_helpers.lua, test/highlights_spec.lua
- **refactor: no longer track update/job counts**
- **refactor: tidy up attach and repo creation**
- **refactor: more misc refactoring**
=> Misc refactoring

lua/gitsigns/attach.lua
=> fix(attach): allow attaching inside .git/

lua/gitsigns.lua, lua/gitsigns/util.lua, lua/gitsigns/watcher.lua
=> fix(attach): detach on when the buffer name changes

lua/gitsigns.lua
=> fix(watcher): workaround weird annoying libuv bug

lua/gitsigns/attach.lua
=> fix(attach): fix worktree attaching

README.md, doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/blame.lua, lua/gitsigns/cache.lua
Similar to fugitive blame.
Resolves #735
with show commit:
=> feat(blame): add `Gitsigns blame`

gen_help.lua, lua/gitsigns/config.lua
These fields haven't been documented for some time, so now hard deprecate them.
=> feat(config)!: deprecate highlight groups in config.signs

lua/gitsigns/blame.lua
Do not override blame winbar set by user
=> fix(blame): respect original blame winbar

lua/gitsigns/current_line_blame.lua
fix a problem caused by commit: https://github.com/lewis6991/gitsigns.nvim/commit/8df63f2ddc615feb71fd4aee45a4cee022876df1
that forgot to fix it in https://github.com/lewis6991/gitsigns.nvim/issues/1072.
=> fix(blame): show current buffer line blame immediately

README.md, doc/gitsigns.txt
Adds default values of `signs_staged` to sample config
=> Add signs_staged to default config in README

lua/gitsigns/git/blame.lua
=> fix(blame): handle incremental output with a buffered reader

doc/gitsigns.txt, lua/gitsigns/config.lua, lua/gitsigns/highlight.lua, lua/gitsigns/signs.lua
Related to https://github.com/lewis6991/gitsigns.nvim/issues/563
=> Add highlights for the cursor line

lua/gitsigns/attach.lua, lua/gitsigns/cache.lua
=> feat: add submodule support for gitsigns urls

lua/gitsigns/blame.lua
=> fix: random errors from blame autocommands (#1139)

lua/gitsigns/manager.lua, lua/gitsigns/signs.lua
Fixes: #929, #1102
Closes: #1152
=> fix: do not mix staged signs with normal signs

doc/gitsigns.txt, gen_help.lua, lua/gitsigns/highlight.lua
=> docs: generate most highlght defs

lua/gitsigns/git.lua, lua/gitsigns/manager.lua
=> fix: do not show staged signs for different bases

lua/gitsigns/attach.lua, lua/gitsigns/manager.lua
=> fix: fileformat autocmd bug

lua/gitsigns/cache.lua, lua/gitsigns/diffthis.lua, lua/gitsigns/git.lua, lua/gitsigns/git/blame.lua, lua/gitsigns/git/repo.lua, lua/gitsigns/git/version.lua
=> fix: support blame for git < 2.41

lua/gitsigns/async.lua, lua/gitsigns/git.lua
=> fix: GitSignsChanged autocmd for staged hunks

lua/gitsigns/config.lua, lua/gitsigns/hunks.lua, lua/gitsigns/manager.lua, test/hunk_spec.lua
=> fix(signs): improve sign generation from hunks

lua/gitsigns/cache.lua, lua/gitsigns/util.lua
=> fix(current_line_blame): last line show not committed

lua/gitsigns.lua
When the branch is changed, the inode for .git/HEAD changes which means we won't get any more change notifications. To fix, we tear down and re-setup cwd_watcher each time it's triggered.
Fixes #1265
=> fix: tracking multiple branch changes

lua/gitsigns/git.lua
Not sure if this is in line with how it's supposed to work or if it would be better to pass in the toplevel somewhere, however I did not see that being the case except when the user explicitly requests it. @ @
=> fix(error): #1277

.luarc.json, lua/gitsigns/attach.lua, lua/gitsigns/git.lua, lua/gitsigns/git/repo.lua, lua/gitsigns/system/compat.lua, test/gitdir_watcher_spec.lua, test/gitsigns_spec.lua, test/gs_helpers.lua, test/highlights_spec.lua
Be more careful about using cwd with system()
=> fix: #1277

lua/gitsigns/git/blame.lua
Occasionally the output from git-blame won't be line buffered and will
sometimes return partial data.
This change adds support for partial lines in the buffered line reader.
Fixes #1236
=> fix(blame): handle partial lines in blame output

lua/gitsigns.lua, lua/gitsigns/git.lua, lua/gitsigns/git/errors.lua, lua/gitsigns/git/repo.lua, lua/gitsigns/qflist.lua, test/gitsigns_spec.lua
Fixes #1117
Fixes #1296
Fixes #1297
=> fix: handle files outside of repo

lua/gitsigns/git/repo.lua
=> fix: #1300

lua/gitsigns/git/cmd.lua
=> fix: remove clear_env=true for system calls

.emmyrc.json, doc/gitsigns.txt, lua/gitsigns/actions.lua, lua/gitsigns/actions/blame.lua, lua/gitsigns/actions/diffthis.lua, lua/gitsigns/actions/show_commit.lua, lua/gitsigns/cache.lua, lua/gitsigns/color.lua, lua/gitsigns/git.lua, lua/gitsigns/git/blame.lua, lua/gitsigns/git/repo.lua, lua/gitsigns/highlight.lua, lua/gitsigns/manager.lua, lua/gitsigns/util.lua, lua/gitsigns/watcher.lua
- Only show summary when cursor is over line.
- highlight all commit lines using the `CursorLine` highlight group.
- add heatmap icon at end of line
=> feat(blame): general improvements

lua/gitsigns/watcher.lua
=> perf: ignore gitdir changes by watchmen
