lewis6991/gitsigns.nvim

doc/gitsigns.txt
lua/gitsigns.lua

Hello!
First off, thank you very much for gitsigns, I didn't realise how slow other solutions were before trying this.
This pull requests allows passing optional options to `next_hunk` and `prev_hunk` to disable wrapping around the file without having to touch the `wrapscan` global option. I used the LSP's [`goto_next` and `goto_prev`](](https://github.com/neovim/neovim/blob/b931a554d70ef07803da3eb3f98ce4b3a3570d11/runtime/lua/vim/lsp/diagnostic.lua#L568-L592)) as inspiration for how the API should look like but I can change to only pass a boolean to the function if you prefer.
Thanks!

Optionally loop around file when navigation hunks.

---

lua/gitsigns.lua
lua/gitsigns/highlight.lua
teal/gitsigns.tl
teal/gitsigns/highlight.tl
test/gitsigns_spec.lua

- Update highlights when the colorscheme is changed
- Refactor existing highlight detection into a function
- Add test to prevent regression
Also, prevent multiple autocmds from being defined if `setup()` is called multiple times, for example when a user reloads their config.
- Define an augroup `gitsigns`
- Clear all autocmds
- Use the augroup in all autocmd definitions
Fixes #105

Fix changing colorschemes breaking color highlight

---

lua/gitsigns.lua
teal/gitsigns.tl

https://user-images.githubusercontent.com/7649265/112881575-8728da00-90d4-11eb-8ff2-4af591d509df.mp4
I had such issue, possibly due to my config:
```lua
vim.wo.signcolumn = 'yes:2'
```

fixed signcolumn local option in floating window

---

lua/gitsigns.lua
teal/gitsigns.tl

Sets cursorline to false in hunk preview window. Having it set makes it hard to distinguish where the preview window starts.

Unset cursorline in hunk preview

---

lua/gitsigns.lua
lua/gitsigns/popup.lua
teal/gitsigns.tl
teal/gitsigns/popup.tl

There's an issue in a3ffb07 where the width is incorrect if the global and local `tabstop` differ because it calculates using the global and then sets it to a different value.

Preview: Set tabstop before calculating width

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/config.lua
lua/gitsigns/git.lua
lua/gitsigns/hunks.lua
lua/gitsigns/status.lua
teal/gitsigns.tl
teal/gitsigns/config.tl
teal/gitsigns/git.tl
teal/gitsigns/hunks.tl
teal/gitsigns/status.tl
test/gitsigns_spec.lua

This allow users to run `lua require"gitsigns".stage_file()` to stage
all changes in a file and `lua require"gitsigns".unstage_file()` to
unstage all changes in a file.
Closes: #127
Also a sidenote, it would be nice to have some sort of "developing" section in readme. Setting up teal isn't the worst, but having the requirements in there would be helpful.

Implemented `stage_buffer` and `reset_buffer_index`

---

README.md
doc/gitsigns.txt
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
teal/gitsigns/config.tl
teal/gitsigns/current_line_blame.tl

This PR adds a configuration option to adjust the `virt_text_pos` for the git blame virtual text.

Configurable blame virtual text position

---

lua/gitsigns/git.lua
teal/gitsigns/git.tl

In #212 I was having some issues with getting line blame working, and from some discussions there you pointed me to #205.
And @benatouba is on to something there. This is definitely something to do with the async of things.
After lots of frustration trying to get to the bottom of this I decided to apply this small change, and now it just seems to work, somewhat to my amazement.
I'm not 100% sure why this fixes things, but it does seem to be a race condition that maybe cancels out the job capture ? Because the problem was that stdout was not being captured (the exit code was 0 so technically everything ran fine).
*PS* Also, I'm very new to the neovim (Lua) API, ecosystem and plenary as well as this plugin so this might work, but maybe not the right solution :D

Fixed race condition in git rev-parse

---

README.md
doc/gitsigns.txt
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
teal/gitsigns/config.tl
teal/gitsigns/current_line_blame.tl
types/types.d.tl

Use a custom timer instead of relying on CursorHold to detach the blame virtial text from `updatetime`.

Added configurable timeout for blame virtual text

---

README.md
doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/actions.lua
lua/gitsigns/config.lua
lua/gitsigns/hunks.lua
lua/gitsigns/repeat.lua
teal/gitsigns.tl
teal/gitsigns/actions.tl
teal/gitsigns/config.tl
teal/gitsigns/hunks.tl
teal/gitsigns/repeat.tl
types/plenary/tbl.d.tl
types/types.d.tl

Fixes #176.
This changes the `stage_hunk` and `reset_hunk` functions such that they accept a range. When given a range they will stage / reset all hunks that intersect with the given range.
Examples:
- lua:
```lua
require"gitsigns".stage_hunk() -- stage the hunk at the cursor
require"gitsigns".stage_hunk({3, 45}) -- stage all hunks in a specific range
require"gitsigns".stage_hunk({vim.fn.line("."), vim.fn.line("v")}) -- stage everything in visual selection
```
- vim command:
```
:Gitsigns stage_hunk
:3,45Gitsigns stage_hunk
:'<,'>Gitsigns stage_hunk
```
The `reset_hunk` variants have the same syntax.

feat: Stage all hunks in a range.

---

Makefile
lua/gitsigns/actions.lua
lua/gitsigns/git.lua
teal/gitsigns/actions.tl
teal/gitsigns/git.tl
test/gitsigns_spec.lua
test/gs_helpers.lua
test/highlights_spec.lua
test/preload.lua

- Make tests more asyn friendly and remove most of the magic sleeps
- Break up into multiple files
- Bypass cmake and call busted directly

Rework testsuite

---

lua/gitsigns/highlight.lua
teal/gitsigns/highlight.tl

Before this commit, the `:highlight link` commands would override
highlight links applied by colorschemes on startup. Now that the
`default` argument is given, the command will respect existing settings,
even if they are links.
See |:hi-default| for more.

fix(highlight): use `:highlight default link`

---

lua/gitsigns/actions.lua
teal/gitsigns/actions.tl

All the lines in the beginning of a commit message with no gaps between them are treated by git as a multiline title.
For example:
```
Title
Also title
Description
```
Currently, if you call `lua require('gitsigns').blame_line(true)` it will show you
```
Title
Description
```
because [`result.summary`](https://github.com/lewis6991/gitsigns.nvim/blob/9940d8bef15e2050fbe27e6cfdfdd8dc64e3593c/lua/gitsigns/actions.lua#L402) stores only the first line of a title.
My solution is to get the whole commit message, rather than concatenating commit's description with its summary.

Fix missing commit description if there's no empty line after title

---

lua/gitsigns/manager.lua
teal/gitsigns/manager.tl

See: https://github.com/neovim/neovim/issues/15147
> require invokes nvim_get_runtime_file which is marked as FAST. however
> as part as its implementation it uses regexes which can invoke
> os_breakcheck which must not be done in FAST functions.
Fixes #272

Don't require in a luv callback

---

lua/gitsigns.lua
lua/gitsigns/actions.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/diff_ext.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
teal/gitsigns.tl
teal/gitsigns/actions.tl
teal/gitsigns/current_line_blame.tl
teal/gitsigns/diff_ext.tl
teal/gitsigns/git.tl
teal/gitsigns/manager.tl
types/plenary/async/async.d.tl
types/plenary/async/util.d.tl

plenary.async requires several modules not used by gitsigns which is
inflating the startup time. Instead just require plenary.async.async.
On an M1 Macbook this appears to half the startup time of gitsigns.

async: require plenary.async -> plenary.async.async

---

README.md
doc/gitsigns.txt

I got this warning that `use_decoration_api` is now removed so I checked here and the option was still on the docs.
Relevant commit on removing the option: https://github.com/lewis6991/gitsigns.nvim/commit/27e1e95e1aa8d4ec0aabbf5148013f58a1bc4b40

remove use_decoration_api from README.md

---

doc/gitsigns.txt
lua/gitsigns/git.lua
teal/gitsigns/git.tl
test/gitsigns_spec.lua

Fixes #292.
Also slightly updated wording in documentation to be precise, but didn't touch README.
I believe some test should be updated but I have problem there. Running `make test` on current 'main' branch gives 20 errors (they seem to be related to branch name being 'HEAD' instead of 'master'). I also see 20 errors with this branch. Maybe it is something with my local setup, I am not sure.
And also didn't find any test dedicated to detached HEAD.

Update status to return short commit hash in detached HEAD

---

lua/gitsigns/util.lua
teal/gitsigns/util.tl

When checking for if on a platform that uses unix style path separators
only linux and osx where take into account. This patch and BSD to that
list.
Tested on: FreeBSD

fix: bsd support

---

doc/gitsigns.txt
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
teal/gitsigns/config.tl
teal/gitsigns/current_line_blame.tl

- Provide b:gitsigns_blame_line_dict for blame info for current line.
Require config.current_line_blame = true.
- Added config.current_line_blame_opts
- Added config.current_line_blame_opts.virt_text. Can be disabled to
disable virtual text. Useful if you want b:gitsigns_blame_line_dict
but without the blame annotation.
- Moved config.current_line_blame_delay to
config.current_line_blame_opts.delay
- Moved config.current_line_blame_pos to
config.current_line_blame_opts.virt_text_pos
- Added deprecation handling for old options
Resolve #199

Rework options for current_line_blame

---

lua/gitsigns/hunks.lua
lua/gitsigns/manager.lua
teal/gitsigns/hunks.tl
teal/gitsigns/manager.tl
test/gitsigns_spec.lua
test/gs_helpers.lua

Speculative signs are added immediately whereas updates are debounced
and throttled for each buffer. If we perform two quick updates which
result in a sign begin added then removed, we need to make sure
speculative signs don't incorrectly persist. Example:
-> buffer change
- speculative signs (#1)
- update (#1)
-> undo (quickly after buffer change)
- speculative signs (#2)
- update (#2)
Update #1 is dropped due to the debounce which results in update #2 not
updating signs due to the hunks not changing. Since signs are never
updated, the speculative signs #1 and #2 will persist.
To get around this, we just need to invalidate the hunks to force a sign
refresh.

fix(update): issue speculative signs persisting

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/actions.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
teal/gitsigns.tl
teal/gitsigns/actions.tl
teal/gitsigns/current_line_blame.tl
teal/gitsigns/git.tl
teal/gitsigns/manager.tl

- Fix duplicate items appearing (#370)
- Make setqflist/setloclist async again
- setqflist('all') now also looks in the current working directory
- Automatically open the quickfix/location list on completion
- Make setloclist an alias of setqflist
- Refactor git.tl so now there is a separate 'Repo' object to allows us
to create git objects for a directory.
Fixes #370

Numerous changes to setqflist

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/config.lua
teal/gitsigns.tl
teal/gitsigns/config.tl
test/gitdir_watcher_spec.lua
test/gitsigns_spec.lua

Some git command likes `git checkout -b` do no update .git/index.
Instead watch the git dir itself to capture all git operations.
Renamed config.watch_index -> config.watch_gitdir
Fixes #377

fix(watcher): watch gitdir instead if index

---

doc/gitsigns.txt
gitsigns.nvim-scm-1.rockspec
lua/gitsigns/actions.lua
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/git.lua
lua/gitsigns/message.lua
teal/gitsigns/actions.tl
teal/gitsigns/config.tl
teal/gitsigns/current_line_blame.tl
teal/gitsigns/git.tl
teal/gitsigns/message.tl

- blame_line() now takes a table as it's first argument (instead of a
boolean) with the fields "full" and "ignore_whitespace"
- Added config.current_line_blame_opts.ignore_whitespace
Resolves #400

feat(blame): Allow to ignore whitespace

---

Makefile
lua/gitsigns/actions.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/manager.lua
lua/gitsigns/util.lua
teal/gitsigns/actions.tl
teal/gitsigns/current_line_blame.tl
teal/gitsigns/manager.tl
teal/gitsigns/util.tl
test/gitsigns_spec.lua

When blaming a line on a file, which as the "dos" fileformat
which is also checked in as a "dos" format including the
carriage returns, gitsigns.nvim currently reports
"Not yet commited" caused by an unsucessfull blame call
to git.
This commit fixes that behavior by appending the carriage
return lines again
Fixes #410 
Starting as a draft, because the tests do not really make sense. Do you have a suggestion, which test helper function to use, to actually test the content of `blame_line()` @lewis6991?

fix(blame_line): Do not omit carriage return

---

lua/gitsigns.lua
teal/gitsigns.tl

Replace bang with force in the command-attributes, since the latter
is equivalent to "command! Gitsigns" when using nvim_add_user_command.
Using bang without force is equivalent to "command -bang Gitsigns".
This closes #433
Signed-off-by: Joshua Wong <joshua99wong@gmail.com>

fix(setup_command): Fix error when redefining Gitsigns

---

doc/gitsigns.txt
lua/gitsigns/actions.lua
lua/gitsigns/config.lua
lua/gitsigns/manager.lua
teal/gitsigns/actions.tl
teal/gitsigns/config.tl
teal/gitsigns/manager.tl

Use virtual lines to show the old version of hunks inline in the buffer.
- Added config.show_deleted
- Added toggle_deleted()
E.g:

feat(): show old version of hunks via virtual lines

---

lua/gitsigns/git.lua
teal/gitsigns/git.tl
test/gitsigns_spec.lua

fix(): support filepaths with unicode characters

---

doc/gitsigns.txt
lua/gitsigns/config.lua
teal/gitsigns/config.tl

Any fields that were deprecated during v0.4 cycle are now
hard-deprecated. They can still be used, but now a warning will appear
on startup.

chore(config)!: hard deprecate fields

---

lua/gitsigns.lua
teal/gitsigns.tl
test/unit_spec.lua
types/types.d.tl

The regular expression in gitsigns.lua did not recognize a path like:
`fugitive:///home/path/to/project/.git//1b441b947c4bc9a59db428f229456619051dd133/subfolder/to/a/file.txt`
Fixed it by adding a missing "/".  This is compatible with PR #152 and still works with git submodules.

fix: gitsigns in fugitive buffer not visible

---

README.md
doc/gitsigns.txt
gen_help.lua
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
teal/gitsigns/config.tl
teal/gitsigns/current_line_blame.tl
test/gitsigns_spec.lua
types/types.d.tl

- config.current_line_blame_formatter can now be specified as a format
string.
- changed default of `config.current_line_blame_formatter` to
'<author>, <author_time:%R> - <summary>' which is equivalent to the
previous function default.
- deprecated config.current_line_blame_formatter_opts

feat(blame): support format strings

---

lua/gitsigns/nvim/autocmds_compat.lua
teal/gitsigns/nvim/autocmds_compat.tl

LuaJIT supports the '%p' format string however PUC Lua does not
(see http://www.lua.org/manual/5.1/manual.html#pdf-string.format).
The autocmd compat module used '%p' to generate id's for Lua callbacks.
This change uses the jit module to detect LuaJIT. If LuaJIT is not
present then '%p' will not be used and instead tostring of the function
with a simple pattern match is used instead.
Fixes: #485

fix(compat): support PUC Lua

---

lua/gitsigns.lua
lua/gitsigns/actions.lua
lua/gitsigns/manager.lua
teal/gitsigns.tl
teal/gitsigns/actions.tl
teal/gitsigns/manager.tl

Sign must be defined before running any updates.
Fixes #490

fix(setup): don't defer setting up signs

---

lua/gitsigns/config.lua
teal/gitsigns/config.tl

Hi 👋 ,
To make the signs more readable, one can use the unicode characters [left half block](https://www.htmlsymbols.xyz/unicode/U+258C), [upper one eighth block](https://www.htmlsymbols.xyz/unicode/U+2594) and [lower one eighth block](https://www.htmlsymbols.xyz/unicode/U+2581).
It looks like this:
Compare it to the default:
Maybe you want to change the default?
Thanks for looking into it and best regards,
David

Make signs thicker

---

lua/gitsigns/git.lua
teal/gitsigns/git.tl

Git blame has a --ignore-revs-file option for specifying a list of SHA's
to exclude. The common convention (according to a quick Google) is to
call this file .git-blame-ignore-revs. Gitsigns will now look for this
file at the top level of the repo and use it if found.
Resolves #459

feat(blame): autodetect .git-blame-ignore-revs

---

lua/gitsigns/git.lua
lua/gitsigns/popup.lua
teal/gitsigns/git.tl
teal/gitsigns/popup.tl
types/types.d.tl

Diffs will still be wrong as we can't detect if the file is binary or
not without using .gitattributes
Fixes: #549

fix: be more graceful with binary files

---

README.md

Telescope removed support for `code_actions`.
See: `help telescope.changelog-1866`
Ref: https://github.com/nvim-telescope/telescope.nvim/pull/1866

doc: telescope no longer supports `lsp_code_actions`

---

doc/gitsigns.txt
lua/gitsigns/config.lua
lua/gitsigns/highlight.lua
lua/gitsigns/manager.lua
teal/gitsigns/config.tl
teal/gitsigns/highlight.tl
teal/gitsigns/manager.tl
test/highlights_spec.lua

Setting GitSignsDeleteLn to anything by default doesn't make much sense
since it ends up highlighting lines not related to the hunk. This is
especially confusing when show_deleted is enabled.
+ Fix incorrect docs.
Fixes #565

fix: don't set default for GitSignsDeleteLn

---

lua/gitsigns/diffthis.lua
teal/gitsigns/diffthis.tl

When opening a diff using diffthis, retain the cursor position from the source window.

feat(diffthis): retain cursor position from source window

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/actions.lua
lua/gitsigns/diffthis.lua
teal/gitsigns.tl
teal/gitsigns/actions.tl
teal/gitsigns/diffthis.tl
types/types.d.tl

When running an action via the :Gitsigns command, the internal plumbing
can now pass the entire command context/options directly to a
specialised action command (per action) that knows how to translate
command parameters to the specific action parameters.
Example 1: `:belowright Gitsigns diffthis` now translates to
`diffthis(nil, {split='belowright'}`.
Example 2: `:6,10Gitsigns stage_hunk` now translates to
`stage_hunk({6,10})`.
Note this change reverts the behaviour of the previous commit that
respects 'splitright'
Fixes #585

feat(command): better processing of command args

---

lua/gitsigns/actions.lua
teal/gitsigns/actions.tl

I think `NormalFloat` is the one to highlight with since it's highlight inside a popup window. I have different backgrounds for a floating window and using `Normal` looks a bit weird.
Before: 
After:

fix(hl): use NormalFloat instead of Normal

---

README.md
doc/gitsigns.txt
lua/gitsigns/config.lua
teal/gitsigns/config.tl

doc: document max_file_length fully

---

README.md
doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/async.lua
lua/gitsigns/config.lua
lua/gitsigns/debug.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
teal/gitsigns.tl
teal/gitsigns/async.tl
teal/gitsigns/config.tl
teal/gitsigns/debug.tl
teal/gitsigns/git.tl
teal/gitsigns/manager.tl
test/gitsigns_spec.lua
test/gs_helpers.lua

Added config.worktrees.
Array of tables with the keys 'gitdir' and 'toplevel'.
If attaching normally fails, then each entry in the table is attempted.
Example:
```lua
worktrees = {
{
toplevel = vim.env.HOME,
gitdir = vim.env.HOME .. '/projects/dotfiles/.git'
}
}
```
Resolves #397

feat: support for detached working trees

---

lua/gitsigns.lua
teal/gitsigns.tl
types/types.d.tl

If Gitsigns is run without a subcommand, then vim.ui.select is called.
Resolves #594

feat(command): use vim.ui.select

---

lua/gitsigns/actions.lua
lua/gitsigns/highlight.lua
teal/gitsigns/actions.tl
teal/gitsigns/highlight.tl

Previously the hunks in the preview windows used GitSigns*Ln highlights.
These are really intended for signs when linehl is enabled and
GitSignsDeleteLn is unset by default.
This change add the highlights GitSignsAddPreview and
GitSignsDeletePreview.

feat(preview): add separate highlights for hunks

---

lua/gitsigns/manager.lua
teal/gitsigns/manager.tl

Sometimes apply_win_signs is called with hunks as nil which throws an error in the second if statement of the function.
I'm unsure if this is expected to happen.
In my case it seemed to occur sometimes when using hydra.nvim with a configuration similar to the one on their [wiki page](https://github.com/anuvyklack/hydra.nvim/wiki/Git#pink-hydra) and opening Neogit's status command.

fix(signs): hunks can be nil

---

lua/gitsigns.lua
teal/gitsigns.tl

I'm getting the following error when calling `bwipeout` on a buffer, so this PR fixes it.
Not sure if this's the best solution since we already have another check [gitsigns.tl#L209-L212](https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns.tl#L209-L212) in the same function.
```
Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:62: The coroutine failed with this message: ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:294: Invalid buffer id: 5
[C]: in function 'nvim_buf_attach'
...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:294: in function 'fn'
...ack/packer/start/gitsigns.nvim/lua/gitsigns/debounce.lua:78: in function 'attach_throttled' …
```

Fix: check if the buffer is still loaded before calling nvim_buf_attach

---

lua/gitsigns/repeat.lua
teal/gitsigns/repeat.tl

I use a non-qwerty layout and so `hjkl` keys are not close to home row,
but instead scattered around the keyboard. Consequently, I remap `l` to
something more convenient.
Recently (it turns out, after commit
9787c94178b4062f30d2f06b6d52984217196647), commands like `Gitsigns
stage_hunk` stopped working, i.e. calling them would not stage the given
hook.
The problem is that `mk_repeatable` assumes a default mapping on `l`
when it calls `normal g@l`. Calling `normal!` fixes this, because then
custom mappings are disregarded and `normal g@l` calls the `stage_hunk`
or whatever was made repeatable.
I believe this should fix #651, although I did not test that.

fix(repeat): support remapped `l` key

---

lua/gitsigns/popup.lua
teal/gitsigns/popup.tl

This commit makes the hunk preview window follow the cursor when scrolling.
To see this behavior, open a preview window using `:Gitsigns preview_hunk`, then use `Ctrl-e` and `Ctrl-y` to scroll the buffer. Without this patch, the window will stay where it was opened. With this patch, the window will change position to be follow the cursor as the buffer scrolls.

Make preview window follow cursor when scrolling

---

lua/gitsigns/popup.lua
teal/gitsigns/popup.tl

Fixes a bug introduced by #705 
Currently, if the hunk preview window is focused and the user moves their cursor inside the preview window, the preview window will gradually move down and too the right by on column and row per move. This is because the floating preview window is incorrectly being adjusted to have its position be relative to the cursor which is offset by the floating window boarder.
This commit updates the `WinScrolled` autocommand introduced by #705 to be scoped to buffer of the file so that this doesn't happen.

fix: don't move preview window while it's focused

---

lua/gitsigns/git.lua
teal/gitsigns/git.tl

- also add BOM stripping
Fixes: #722

fix: don't run iconv on utf-16

---

lua/gitsigns/highlight.lua
teal/gitsigns/highlight.tl

fix(highlight): apply fallback even if not defined

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/git.lua
teal/gitsigns.tl
teal/gitsigns/git.tl
test/gitdir_watcher_spec.lua
test/gitsigns_spec.lua
test/gs_helpers.lua

feat: Enable `attach()` to work with any buffer when given context data.

---

doc/gitsigns.txt
lua/gitsigns/config.lua
teal/gitsigns/config.tl

When using `current_line_blame = true` with a highlight that defines a `bg`, the virtual text has a space at the beginning but not at the end. This looks a bit off (e.g.: the virtual text looks like a small label with the text not properly aligned).
This is invisible when using a highlight without `bg`.
This small changes adds a space at the end so that virtual text in such situations makes better sense visually.
Fixes: https://github.com/lewis6991/gitsigns.nvim/issues/745

Add space at the end of blame virtual text

---

.github/workflows/ci.yml

If we change ci.yml or Makefile we should to rebuild all supported
neovim versions again. For example, if we accidentally remove a
dependency that works as expected on nightly but not on v0.7.2 we need
the CI job to fail immediately.

ci: add ci.yml and Makefile as part of the cache key

---

.github/workflows/ci.yml
Makefile

Clang has faster link time optimization by default, which will should
save 10-20 seconds per CI run.

ci: use clang instead of gcc compiler

---

.github/workflows/ci.yml

Also prefer apt-get over apt to not trigger the "apt has no stable CLI
interface" warning.

ci: don't install unnecessary former neovim dependencies

---

lua/gitsigns/manager.lua
teal/gitsigns/manager.tl

I would get an error when running `gs.toggle_deleted(true)` from a [hydra.nvim](https://github.com/anuvyklack/hydra.nvim) setup function.
Error message:
```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:274: bad argument #1 to 'ipai
rs' (table expected, got nil)                                                                                                                                                                                                                 …
```

fix show_deleted when buffer not in cache

---

README.md

`vim.fs` used in https://github.com/lewis6991/gitsigns.nvim/blob/f412f51d0eaf0905a2759c8087090071689bb8fb/teal/gitsigns.tl#L27 was added in nvim 0.8.0 (https://github.com/neovim/neovim/releases/tag/v0.8.0), but the current readme still states nvim >= 0.7.0 is required.
I saw that 0.7.x has been dropped in CI (https://github.com/lewis6991/gitsigns.nvim/blob/main/.github/workflows/ci.yml), so this PR updates the readme to require 0.8.

docs: require nvim 0.8+ in readme

---

README.md

The updated mapping examples for staging and resetting hunks in visual mode added in https://github.com/lewis6991/gitsigns.nvim/commit/5d840679cfba0a93b28ba573f982613ca25d3909 result in an error, because they reference an undefined `line()` function.
This PR corrects this to `vim.fn.line()`.

fix(README): correct undefined `line()` to `vim.fn.line()`

---

lua/gitsigns/manager.lua
teal/gitsigns/manager.tl

checks signs_normal is not nil to avoid crashing when starting by invoking toggle_current_line_blame
fixes: #796

fix(toggle_current_line_blame): check signs_normal is not nil

---

lua/gitsigns/signs/vimfn.lua
teal/gitsigns/signs/vimfn.tl

fix: staged_signs with legacy signs

---

lua/gitsigns/git.lua

Fix no commit message.
After fix

fix: no commit message

---

lua/gitsigns/git.lua

My git version is `git version 2.42.0-rc0`.
This causes the following error because the patch number includes a string.
```lua
  Error  04:43:36 PM msg_show.lua_error     Error executing luv callback:
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:74: assertion failed!
[C]: in function 'assert'
...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:74: in function 'parse_version'
...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:121: in function '_set_version'
...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:135: in function 'git_command'
...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:424: in function 'new' …
```

fix: git rc release version causes assertion error

---

lua/gitsigns/watcher.lua

As per comment in https://github.com/lewis6991/gitsigns.nvim/issues/848#issuecomment-1668828577 the gitdir watcher sometimes erroneously receives a nil filename from `luv`/`libuv`.

fix: accommodate watcher receiving a nil filename.

---

lua/gitsigns/current_line_blame.lua

```log
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: ...m/lazy/gitsigns.nvim/lua/gitsigns/current_line_blame.lua:154: attempt to index local 'bcache' (a nil value)
...m/lazy/gitsigns.nvim/lua/gitsigns/current_line_blame.lua: in function 'handle_blame_info'
...m/lazy/gitsigns.nvim/lua/gitsigns/current_line_blame.lua:238: in function <...m/lazy/gitsigns.nvim/lua/gitsigns/current_line_blame.lua:184>
[C]: in function 'error'
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'cb'
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:113: in function 'cb'
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:186: in function …
```

fix(blame): If it has been detached, the cache[bufnr] is nil

---

lua/gitsigns.lua
lua/gitsigns/config.lua

This fixes the signature of setup to allow now parameters (nil). 
Otherwise I would get an error:

Fixes the signature of setup to not require an argument

---

lua/gitsigns/actions.lua
lua/gitsigns/util.lua

The fix of https://github.com/lewis6991/gitsigns.nvim/issues/779 in https://github.com/lewis6991/gitsigns.nvim/pull/862 broke `setqflist`. An empty hunk is being added to the quickfix for each changed file and no hunks is being added for a newline appended to a file.
`Repo:get_show_text` is used to retrieve the lines of the index state and `utils.file_lines` is used to retrieve the lines of the working tree state. The trailing empty line is being retained by `Repo:get_show_text` (by providing `{ raw = true }` to [Repo:command](https://github.com/lewis6991/gitsigns.nvim/blob/907ae8636016aab2f283576fc60d46ca3427e579/lua/gitsigns/git.lua#L324)) https://github.com/lewis6991/gitsigns.nvim/blob/907ae8636016aab2f283576fc60d46ca3427e579/lua/gitsigns/git.lua#L404-L405 but not `utils.file_lines` …

fix(setqflist): don't strip trailing newline from working tree state

---

doc/gitsigns.txt
etc/doc_template.txt
lua/gitsigns/actions.lua
lua/gitsigns/attach.lua
lua/gitsigns/cache.lua
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/git.lua
lua/gitsigns/util.lua
test/gitsigns_spec.lua

Limits the amount of git-blame processes in the background to 1
Previously current_line_blame would run a git-blame process per line
(via the `-L` flag) in an attempt to be more efficient. However after
some investigation it seems that running git-blame for the entire file
rarely exceeds 2x the time it takes to run for a single line, even for
large files.
This change alters current_line_blame to run git-blame for the entire
file after each buffer edit and caches that in memory. This makes the
first git-blame after an edit ~2x slower, but makes any cursor movements
after that instant.
A follow-up to this would be for current_line_blame to track buffer
updates to avoid the cache needing to be invalidated on every edit.
Fixes #877

perf(blame): general improvements

---

lua/gitsigns/actions.lua

For `:Gitsigns next_hunk`, `:Gitsigns prev_hunk` and `:Gitsigns blame_line`, named arguments aren't working. For example, `:Gitsigns blame_line full=true` does not display the "full" blame popup, and behaves identically to `:Gitsigns blame_line`.
I've just added three wrapper functions to the `C` table, which seems to solve the issue for me. From what I can tell, the logic in `lua/gitsigns/cli.lua:106` dealing with named arguments isn't needed, since all of the the functions in `gitsigns.actions` that use named arguments (ie a table) now have wrappers in `C` - but I haven't changed anything there because I'm not confident it won't break anything :)

fix(cli): named args not working

---

lua/gitsigns/actions.lua
lua/gitsigns/attach.lua
lua/gitsigns/cache.lua
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
lua/gitsigns/util.lua
lua/gitsigns/watcher.lua

The blame cache is now maintained in the CacheEntry object
and invalidated incrementally on buffer updates.
In addition git-blame is bypassed if the cursor line is within a hunk.

perf(blame): better cache invalidation

---

doc/gitsigns.txt
etc/doc_template.txt
lua/gitsigns/attach.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
test/gitsigns_spec.lua

The `base` can now be set to `FILE` to diff against the working version.
Resolves #164

feat(diff): allow to diff against the working version

---

lua/gitsigns/actions.lua

fix(actions): set less lines when reseting hunks

---

README.md
doc/gitsigns.txt

Add the default value of `config.current_line_blame_opts.virt_text_priority` to the README setup example.

fix(README): add default config.current_line_blame_opts.virt_text_priority

---

lua/gitsigns/cli.lua

The `:Gitsigns` command prompts the user for an action via [`vim.ui.select`](https://neovim.io/doc/user/lua.html#vim.ui.select()) when called without arguments,  which yields `nil` when the dialog is cancelled.
Currently, this is not checked and if the user cancels the dialog, an error message is displayed: 'nil is not a valid function or action'. This PR simply returns from `cli.run()` silently if the `vim.ui.select` prompt was cancelled.

fix: error message when `:Gitsigns` select dialog is cancelled

---

lua/gitsigns.lua

Attempt to fix #903.
This bug is triggered when opening neovim inside a directory, with both neo-tree and this plugin installed.
Opening the directory causes neovim to create a netrw buffer.
When the `setup()` function of this plugin is called, the plugin will eventually reach this particular part of the code:
https://github.com/lewis6991/gitsigns.nvim/blob/37d26d718f8120a8c5c107c580c8c98cf89fdf1f/lua/gitsigns.lua#L122-L128
At this point in time, the netrw buffer exists, so `M.attach()` will be called with that buffer. `M.attach()` will eventually give up control here with `async.scheduler_if_buf_valid()`:
https://github.com/lewis6991/gitsigns.nvim/blob/37d26d718f8120a8c5c107c580c8c98cf89fdf1f/lua/gitsigns/attach.lua#L296-L299
After giving up control, the neotree plugin will run the …

fix: gitsigns not automatically attached due to async not returning

---

test/gitsigns_spec.lua

Fixing failing tests on nvim nightly due to the default colorscheme change.

test: use the classic vim colorscheme for nvim nightly

---

lua/gitsigns/manager.lua

Problem: If `buf_check(...)` fails (mostly when cache is outdated), it
would abort updating gitsigns, but this actually leads to the coroutine
never resolving and stuck forever. It is because the asynchronous
callback `cb()` is never called.
As a result, gitsigns might be stuck forever and fail to update silently
(see #924), and manual reattach or refresh also doesn't work, because of
the unresolved coroutine that is recognized to be "still running", i.e.,
any subsequent calls to "throttled" `manager.update()` will not be
executed.
Solution: Make `buf_check()` always yield a value (true/false) to ensure
that `manager.update()` will resolve and finish its execution after all.

fix(manager): manager.update() never resolve when buf_check() fails

---

lua/gitsigns/diffthis.lua
lua/gitsigns/util.lua

When scanning for CRLF do not check EOF.
Fixes #927

fix(dos): correct check for dos files

---

README.md
doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/config.lua

In my own workflow I prefer to attach gitsigns manually whenever I need it. This adds a configuration flag to accommodate this.

feat: configurable auto attach

---

README.md

The previous link was pointing to the nvim-lua-guide project that has been archived in December 2022.

fix: update lua-guide link in README

---

lua/gitsigns/hunks.lua
lua/gitsigns/manager.lua

Since linematch will report a changed line following deleted lines as multiple hunks on a single line, it will only show the `changed` sign and will drop the `deleted` sign.  To fix this check for overlapping hunks and mark the change hunk as changedelete.
Fixes #701 in part

fix: changedelete symbol with linematch enabled

---

.github/workflows/luarocks.yml

Hey :wave: 
This PR is part of a push to get neovim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
See also:
- [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
- [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html).
- Add a workflow that publishes tags to luarocks.org when a tag or release is pushed.
- Tagged releases are installed locally and then published to luarocks.org.
- For the luarocks workflow to work, someone with a luarocks.org account will have to add their [API key](https://luarocks.org/settings/api-keys) to this repo's [GitHub actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).
- Due to a shortcoming in …

feat: publish releases to luarocks

---

README.md
doc/gitsigns.txt

The default text sign for add and change is a "Box Drawings Heavy Vertical" (U+2503). However, README.md uses "Box Drawings Light Vertical" (U+2502) in its configuration for these signs. This commit changes the sample configuration to match the actual defaults used in the code, which then gets propagated to gitsigns.txt when running gen_help.lua.
This way someone who wants to use the same symbol for untracked as add and change, as I did, gets the same character when they copy and paste from the documentation into their config.

Change README.md configuration signs to match actual defaults

---

README.md
doc/gitsigns.txt
gen_help.lua
lua/gitsigns/actions.lua
lua/gitsigns/hunks.lua

- Deprecated `next_hunk()` and `prev_hunk()`.
- Can now navigate to the first/last hunk using `nav_hunk('first'|'last')`.
- Added `count` to navigation options. Defaults to `v:count1`.
- Updated recommended keymaps for navigation.
- Navigation actions now navigate to the first non-blank column.

feat(nav): add nav_hunk()

---

lua/gitsigns/diff_int.lua
lua/gitsigns/hunks.lua
test/actions_spec.lua

Previously when diffing two files where one did not have a newline at
the end of the file, gitsigns was unable to stage such differences since
this information was not captured during the diff stage.
If you run `vim.diff('a', 'a\n')` you get the result:
@@ -1 +1 @@
-a
\ No newline at end of file
+a
However if you run `vim.diff('a', 'a\n', {result_type='indices'})` you
get:
{ {1, 1, 1, 1} }
And since Gitsigns tracks changes as a list of text lines, the
information about a missing newline at the end of the file is not
correctly tracked.
The main consequence of this is that staging hunks which contain these
lines would result in an error as the generated patch would not apply
since it was missing "\ No newline at end of file".
To fix this, the internal hunk object now tracks this end of file …

fix(stage): staging of files with no nl at eof

---

Makefile

It currently assumes lua-language-server is in PATH, which may not be
true.

build: use downloaded lua-language-server

---

lua/gitsigns/git.lua

`not` has higher precedence than `~=`, so it was actually `(not #git_command(..)) ~= 0`.
To fix it, we can simplify the double negation as just a `==`.

fix(yadm): correct ls-files check

---

lua/gitsigns/actions.lua
lua/gitsigns/manager.lua
lua/gitsigns/util.lua

Seems that `nvim__buf_redraw_range` was deprecated in https://github.com/neovim/neovim/pull/28101.

fix: use latest api in 0.10

---

lua/gitsigns/actions.lua
lua/gitsigns/attach.lua
lua/gitsigns/cache.lua
lua/gitsigns/debug.lua
lua/gitsigns/debug/log.lua
lua/gitsigns/diffthis.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua
lua/gitsigns/util.lua
lua/gitsigns/watcher.lua
test/gitdir_watcher_spec.lua
test/gitsigns_spec.lua

fix(update): always update file info when refreshing compare text

---

lua/gitsigns/current_line_blame.lua

When using `virt_text_pos = 'right_align'`, the placement strategy sometimes doesn't switch to `'eol'` (to avoid overlaps) until it's too late.
When the blame text's length exceeds the available space to the right of the buffer's text, the intention is to switch to the 'eol' extmark placement. However, there were a number of issues that could trip up the time at which it swtiches to 'eol':
- if the buffer line or virtual text contain multibyte characters, they weren't counted properly in terms of screen cells that they'd consume
- incorrect window identifer was passed when calculating the available space, meaning that signs/folds/numbers columns weren't properly accounted for.
<details>
<summary>Before (using reproduction steps below)</summary> …

fix(blame): avoid right-aligned blame overlapping buftext

---

doc/gitsigns.txt
lua/gitsigns.lua
lua/gitsigns/git/version.lua
test/gs_helpers.lua

Previously `setup()` was asynchronous in order to run a system command
to check the git version.
As support for v0.8 is dropped, this is no longer required.

feat(setup)!: make setup() synchronous

---

lua/gitsigns/watcher.lua

Throttle (in addition to debounce) in case the debounce delay is not
enough and to prevent too many handlers from being launched (and
interleaved).

fix(watcher): throttle watcher handler

---

lua/gitsigns/attach.lua
lua/gitsigns/git.lua
lua/gitsigns/manager.lua

Previously when attaching to a commit buffer (via gitsigns or fugitive),
gitsigns would set the revision to diff against to the parent so the
signs of that commit would be displayed.
Now that we have staged signs, they are now used for that purpose, and
so the base is no longer set to the parent.

feat: tweak how commit buffers are processed

---

README.md
doc/gitsigns.txt
lua/gitsigns/config.lua
lua/gitsigns/current_line_blame.lua
lua/gitsigns/util.lua

- Also make relative time the default time format for current_line_blame_formatter
- When `current_line_blame_formatter` is passed as a function it is no longer passed an opts argument.

feat!: remove current_line_blame_formatter_opts

---

lua/gitsigns/attach.lua

Only attach to fugitive buffers for files, not directories.
Resolves #1057

fix(attach): resolve error viewing fugitive trees

---

doc/gitsigns.txt
lua/gitsigns/actions.lua
lua/gitsigns/blame.lua
lua/gitsigns/cache.lua
lua/gitsigns/config.lua
lua/gitsigns/diffthis.lua
lua/gitsigns/git.lua
lua/gitsigns/git/blame.lua

- Ensure ':Gitsigns blame' utilizes the blame cache.
- Rewrite the blame runner to process output incrementally.
- Make the blame cache more efficient.
- Move the blame processing code to a separate module.

perf(blame): some improvements

---

lua/gitsigns/blame.lua

It causes the two-window not to align correctly if the main window has a `'winbar'`.

fix(blame): show the winbar if the main window has it enabled

---

lua/gitsigns/manager.lua
lua/gitsigns/watcher.lua
test/gitdir_watcher_spec.lua

Now the watcher handlers is debounced and throttled, the ignore list
is no longer necessary.
This avoids an issue where we sometimes trigger the handler too early
(as other files are still changing). Now the debounce and throttle logic
and take into account every single file change.

fix(watcher): do not ignore any updates

---

lua/gitsigns/blame.lua

Fix blame window render error: `end_col` out of range. Resolve #1050 and #1073
The reason of this error is that the `00000000 Not Committed Yet` line is different than `max_author_len`.

fix(blame): render blame end_col out of range

---

doc/gitsigns.txt
gen_help.lua

The default filetype detection algorithm only checks the last lines of
.txt files for "ft=help" before setting the filetype to "text". Since
there was an empty line at the end, the help page was getting marked as
having filetype text first, and then help, which meant both autocmds
were triggered. This fixes that by removing the extraneous newline; note
that there is still a newline at the end of file, as is customary, and
this just removes the second, unnecessary newline.
Furthermore, this simplifies the logic for "gen_help.lua" and increases
its robustness by using the "io.lines" function rather than reading the
entire file as a string and using regular expressions to split it into
lines.

fix: help triggering text autocmds

---

lua/gitsigns/highlight.lua

The `GitSignsStagedTopdeleteCul` highlight (especially the foreground) was very hard to read. It seems the issue was that `GitSignsStagedTopdeleteCul` incorrectly derived from `GitSignsStagedDeleteCul` instead of the expected `GitSignsTopdeleteCul`.
So I think the `fg_factor` ended up being `0.5` of `0.5` equals `0.25`, foreground extremely dim.
Likely just a simply cut-and-paste oversight.
With this change the dim problem goes away.

fix: derive Staged*Cul highlight correctly

---

lua/gitsigns/blame.lua

Hello!
Current file type name `gitsigns.blame` does not allow a user to setup a `ftplugin` file.
Neovim does not pick up a file named `gitsigns.blame.lua` (or `gitsigns.blame.vim` for that matter).
`:h ftplugin-name` does not mention how to work around that limitation.
This PR fixes that behaviour.

fix(blame)!: replace dot with dash in blame file type name

---

lua/gitsigns/blame.lua

This causes `wrap` to be disabled and causes `scrollbind` to be enabled so `<C-w>s` behaves strangely.

fix(blame): restore original options when blame window is closed

---

lua/gitsigns/actions.lua
lua/gitsigns/git/repo.lua

If change_base is called, instead of run git status, run git diff against the changed base_commit.
Fix: #692

fix: setqflist("all") should respect change_base

---

lua/gitsigns/actions.lua

Fixes #1113
`gitsigns.hunks.find_nearest_hunk`'s algorithm only works on a sorted list of hunks (because it returns `i+1` which it assumes is the next hunk), however `get_nav_hunks` did not return the list of hunks sorted.
So `get_nav_hunks` might return a list with lines 16, 29, 24 (staged hunks appended to unstaged); then when jumping from 16 to the next hunk, it would find and jump to 29 when you would expect it to find the hunk at line 24.
I'm not familiar with the codebase, but this does not look like it will break anything else. `find_nearest_hunk` is only used in `nav_hunk`.

fix: sort get_nav_hunks to handle mixed hunk states

---

lua/gitsigns/actions.lua

My default for opening splits is vertical. I try to open `diffthis` in vertical:
```lua
require('gitsigns').diffthis { '', vertical = false }
```
It still opens the diff vertically.
The error is that the value is replaced by the default because it compares the argument as a bool instead of comparing with `nil`.

fix: diffthis vertical option

---

lua/gitsigns/highlight.lua

This PR fixes an issue where where highlight groups which only define `cterm*` fields wouldn't be considered by `highlight.lua`.

fix: handle terminal-only highlights

---

lua/gitsigns/blame.lua

Fixes https://github.com/lewis6991/gitsigns.nvim/issues/1121
1. `show_commit()` always creates a new buffer and set its name according to the SHA1
2. that buffer is never wiped
3. when calling `show_commit()` twice on the same commit, we end up trying to create a 2nd buffer with the same name as a preexisting one
```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:95: The async coroutine failed: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/blame.lua:194: Failed to rename buffer
[C]: in function 'nvim_buf_set_name'
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/blame.lua:194: in function <...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/blame.lua:188>
[C]: in function 'error' …
```

fix(blame): show same commit twice or more

---

lua/gitsigns/attach.lua
lua/gitsigns/diffthis.lua

fix: improve support for worktrees in bare repos

---

lua/gitsigns/popup.lua

Hey everyone,
I noticed that after closing the blame_line/preview_hunk window, the buffer is not wipeout, which causes a [Scratch] entry to remain in the buffer list. With frequent opening and closing of these windows, the buffer list can become cluttered.
To better explain this issue, I recorded a video.
https://github.com/user-attachments/assets/01c7dade-d4f0-46d4-8de7-7f3e2f40e75c
Since I haven't fully read all the code yet, I'm not sure if this will cause other side effects. Regardless, this is an attempt.
Best wishes, and take care!

fix: After closing the blame_line/preview_hunk window, the buffer should be wipeout.

---

lua/gitsigns/blame.lua
lua/gitsigns/cache.lua

fix(blame): ensure blame object is valid when all lines are requested

---

README.md
doc/gitsigns.txt
gen_help.lua
lua/gitsigns/actions.lua
lua/gitsigns/config.lua

- Deprecated config.show_deleted and toggle_deleted()
- Use preview_hunk_inline()
- Deprecated undo_stage_hunk()
- Use stage_hunk() on staged lines
- Updated keymap suggestion in README.md
- Removed hidden option config._inline2

feat!: deprecate some functions

---

lua/gitsigns/git.lua
lua/gitsigns/util.lua
test/actions_spec.lua

- When staging files, convert the text into a string before passing to
system() to ensure EOL is respected.
- When setting lines. If text doesn't end with an empty line then set
'eol=false'.
Fixes #1145

fix: more EOL fixes

---

.gitignore

It's generated when running `make luals-check`.

build: add check.json to .gitignore

---

lua/gitsigns/config.lua

This will remove stack traces from `:checkhealth vim.deprecated`.

fix: use non-deprecated versions of vim.validate

---

README.md
lua/gitsigns/actions.lua

Previous type vih will only select hunk lines which are below current line with mapping like
`map({ "o", "x" }, "ih", "<cmd>Gitsigns select_hunk<CR>")`.
Also update the readme to use the faster `<cmd>` mapping.

fix(select_hunk): compatible with <cmd> mapping

---

test/gs_helpers.lua

Nightly now sets linematch by default. Force it off in tests.

ci: fix nightly

---

lua/gitsigns/cache.lua
test/actions_spec.lua

I recently noticed some unexpected behavior when using `stage_hunk` on a staged hunk (previously it work like `undo_stage_hunk`)
Not sure if it's a regression: https://github.com/lewis6991/gitsigns.nvim/blob/b95d08a0607328d7d973cfcdaf4133a1a5fb3f2e/lua/gitsigns/actions.lua#L157-L171

fix: `stage_hunk` on staged hunk should behave like `undo_stage_hunk`

---

.github/workflows/ci.yml
lua/gitsigns/watcher.lua

Make it so `Git rm %` doesn't cause an error.

fix(watcher): invalidate the cache earlier

---

lua/gitsigns/preview.lua

Switch from `normal! zR` to `set nofoldenable` for inline preview window, which not only unfolds everything, but prevents folds from being created in the future. Addresses an issue when used with kevinhwang91/nvim-ufo.

fix: prevent inline hunk preview from folding

---

lua/gitsigns/hunks.lua

Problem:
`blame_line({full=true})` can stop work after
https://github.com/lewis6991/gitsigns.nvim/commit/095a58efbd5aec16217e2a90b1fdc0ba9bf6ab27,
Reproduction:
* cd path/to/gitsigns.nvim
* `nvim README.md +3`
* `:lua require('gitsigns').blame_line({full=true})`
Solution:
`table.insert(t, obj)` seems suppress type check for `start_row`, use `t[#t + 1] = obj` instead.

fix: blame_line{full=true} stop work

---

lua/gitsigns/git/repo.lua

`errors.w` doesn't have `path_does_not_exist` but `errors.e` does., will err on git commit buffers or shell command line editing with `export EDITOR=nvim`.

fix: errors nil ref

---

lua/gitsigns/nav.lua

Navigation won't open a new preview popup if there is one since 9296d3048dd1f13c642f08f392fb22a256061d50. I believe this is due to `nav_hunk` moves the cursor before checking `Popup.is_open('hunk')`, and `autocmd CursorMoved` created by `Popup.create` will close the popup, so it will never open a new popup if `opt.preview` is not set.

fix: check preview popup before navigating

---

lua/gitsigns/hunks.lua

Problem: when fileformat change from unix to dos,
`blame_line{full=true}` throw error:
```
vim.schedule callback:
/home/phan/lazy/gitsigns.nvim/lua/gitsigns/popup.lua:168: {
end_col = 46,
hl_group = "GitSignsAddInline",
start_col = 44,
start_row = 38
}
Invalid 'end_col': out of range
```
Solution: ensure run_word_diff and nvim_buf_set_extmark both use striped
version
Example: run `blame_line{full=true}` on this file https://github.com/microsoft/vcpkg/blob/8b4801fb4aba2e5f5667aa89d958d94cfc17c1d0/ports/apsi/fix-find-seal.patch#L10.

fix: when diff dos format with unix format

---

lua/gitsigns/highlight.lua

This PR fixes an issue where staged colors appeared too dark and hard to distinguish on light backgrounds. The previous algorithm did not properly account for different background themes, leading to poor contrast.
With this fix, staged colors now dynamically adapt based on whether the background is light or dark, ensuring better visibility and contrast in both themes.
In the screenshot above, staged colors in the light color scheme are getting too dark to be able to tell apart.
After this fix is applied, staged colors now get lighter on a light color scheme, and vice versa.

fix: calculate staged color dynamically adjust based on background

---

lua/gitsigns/git.lua

[This commit](c80e0b4bfc411d5740a47adc8775fd1070f2028b) introduced a check, as I understand, to avoid attaching to files inside `.git` dir. Turns out it also make it not attach to `.gitignore` at the root of the repo, for example. Adding this log confirms it:
```diff
diff --git a/lua/gitsigns/git.lua b/lua/gitsigns/git.lua
index a319558..b431451 100644
--- a/lua/gitsigns/git.lua
+++ b/lua/gitsigns/git.lua
@@ -249,6 +249,8 @@ function Obj.new(file, revision, encoding, gitdir, toplevel)
return
end
+  vim.print(vim.fn.fnamemodify(file, ':p'), repo.gitdir)
+
if vim.startswith(vim.fn.fnamemodify(file, ':p'), repo.gitdir) then
-- Normally this check would be caught (unintended) in the above
-- block, as gitdir resolution will fail if `file` is inside a gitdir.
```
The output when I open a …

fix(attach): don't skip all `.git*` files at the root of the repo

---

lua/gitsigns/cache.lua

```
Gitsigns change_base ~
Gitsigns next_hunk target=all
```
```
Lua :command callback: **/gitsigns.nvim/lua/gitsigns/cache.lua:228: assertion failed!
[thread: 0x7f08cc0c7e78] [C]: in function 'assert'
[thread: 0x7f08cc0c7e78] **/gitsigns.nvim/lua/gitsigns/cache.lua:228: in function 'get_hunks'
[thread: 0x7f08cc0c7e78] **/gitsigns.nvim/lua/gitsigns/actions/nav.lua:74: in function 'get_nav_hunks'
[thread: 0x7f08cc0c7e78] **/gitsigns.nvim/lua/gitsigns/actions/nav.lua:100: in function 'nav_hunk'
[thread: 0x7f08cc0c7e78] **/gitsigns.nvim/lua/gitsigns/actions.lua:458: in function <**/gitsigns.nvim/lua/gitsigns/actions.lua:455>
[thread: 0x7f08cc75e4f8] [C]: in function 'error'
[thread: 0x7f08cc75e4f8] **/gitsigns.nvim/lua/gitsigns/async.lua:230: in function '_finish'
[thread: …
```

fix: error when `Gitsigns next_hunk target=all`

---

lua/gitsigns/actions/blame.lua

This is a super simple UI improvement. It's just that if I have `list` and `listchars` set globally, the blame window looks ugly:
With my PR:

fix(blame): set nolist in the blame window

---

.github/workflows/ci.yml
lua/gitsigns/git/repo.lua
test/gitdir_watcher_spec.lua
test/gitsigns_spec.lua

- Fix issue of watcher callback not being called when running
with Watchman due to filename ignore check being done in the
debounced section of the handler.
- Only update abbrev_head when `.git/HEAD` is changed
- Reduce watcher timer debounce interval to 200ms.
- Add handwritten implementation of `git rev-parse --abbrev-ref HEAD`
which reads `.git/HEAD` directly.

feat: overhaul repo watcher

---

lua/gitsigns/actions/blame.lua

This PR addresses #1405 and #1388, which are caused by the incompatible function signature `vim.str_utfindex` in Neovim v0.11.
- `vim.str_utfindex` before 0.11:
```lua
--- @param str string
--- @param index? integer
--- @return integer UTF-32 index
--- @return integer UTF-16 index
function vim.str_utfindex(str, index) end
```
- `vim.str_utfindex` since 0.11:
```lua
--- Parameters:
--- {s} (string)
--- {encoding} ("utf-8"|"utf-16"|"utf-32")
--- {index} (integer)
--- {strict_indexing} (boolean?) default: true
--- Return:
--- (integer)
vim.str_byteindex(s, encoding, index, strict_indexing)
```
At first, I considered simply using a helper function to wrap the incompatible functions, but that felt too tedious for such a common task. Then I found the vimscript API function …

fix: blame incompatible neovim function
